package Day07;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

public class Day07p2 {
    public static final char LASER_ORIGIN = 'S';
    public static final char SPLITTER = '^';

    public static long getSolution() {
        List<String> lines = loadLinesFromFile("src/Day07/input.txt");
        String startLine = lines.removeFirst();
        long[][] pathCounts = new long[lines.size()][startLine.length()];
        pathCounts = propogateLaser(lines, startLine.indexOf(LASER_ORIGIN), 0, pathCounts);

        return pathCounts[0][startLine.indexOf(LASER_ORIGIN)];
    }

    public static long[][] propogateLaser(List<String> lines, int laserIndex, int linesIndex, long[][] timeLinesCount) {
        if (lines.size() <= 1) {
            timeLinesCount[linesIndex][laserIndex] = 1;
            return timeLinesCount;
        }

        String newLine = new String(lines.getFirst());
        List<String> newLines = lines.subList(1, lines.size());

        if (newLine.charAt(laserIndex) != SPLITTER) {
            if (timeLinesCount[linesIndex + 1][laserIndex] > 0) {
                timeLinesCount[linesIndex][laserIndex] = timeLinesCount[linesIndex + 1][laserIndex];
                return timeLinesCount;
            }
            timeLinesCount = propogateLaser(newLines, laserIndex, linesIndex + 1, timeLinesCount);
            timeLinesCount[linesIndex][laserIndex] = timeLinesCount[linesIndex + 1][laserIndex];
            return timeLinesCount;
        }

        timeLinesCount = propogateLaser(newLines, laserIndex - 1, linesIndex + 1, timeLinesCount);
        timeLinesCount = propogateLaser(newLines, laserIndex + 1, linesIndex + 1, timeLinesCount);
        timeLinesCount[linesIndex][laserIndex] = timeLinesCount[linesIndex + 1][laserIndex + 1] + timeLinesCount[linesIndex + 1][laserIndex - 1];

        return timeLinesCount;
    }

    public static List<String> loadLinesFromFile(String filePath) {
        List<String> lines = new ArrayList<>();
        try (BufferedReader reader = new BufferedReader(new FileReader(filePath))) {
            String line;
            while ((line = reader.readLine()) != null) {
                lines.add(line);
            }
        } catch (IOException e) {
            System.err.println("Error reading file: " + e.getMessage());
        }
         return lines;
    }
}

/*
--- Part Two ---
With your analysis of the manifold complete, you begin fixing the teleporter. However, as you open the side of the teleporter to replace the broken manifold, you are surprised to discover that it isn't a classical tachyon manifold - 
it's a quantum tachyon manifold.

With a quantum tachyon manifold, only a single tachyon particle is sent through the manifold. A tachyon particle takes both the left and right path of each splitter encountered.

Since this is impossible, the manual recommends the many-worlds interpretation of quantum tachyon splitting: each time a particle reaches a splitter, it's actually time itself which splits. In one timeline, the particle went left, 
and in the other timeline, the particle went right.

To fix the manifold, what you really need to know is the number of timelines active after a single particle completes all of its possible journeys through the manifold.

In the above example, there are many timelines. For instance, there's the timeline where the particle always went left:

.......S.......
.......|.......
......|^.......
......|........
.....|^.^......
.....|.........
....|^.^.^.....
....|..........
...|^.^...^....
...|...........
..|^.^...^.^...
..|............
.|^...^.....^..
.|.............
|^.^.^.^.^...^.
|..............
Or, there's the timeline where the particle alternated going left and right at each splitter:

.......S.......
.......|.......
......|^.......
......|........
......^|^......
.......|.......
.....^|^.^.....
......|........
....^.^|..^....
.......|.......
...^.^.|.^.^...
.......|.......
..^...^|....^..
.......|.......
.^.^.^|^.^...^.
......|........
Or, there's the timeline where the particle ends up at the same point as the alternating timeline, but takes a totally different path to get there:

.......S.......
.......|.......
......|^.......
......|........
.....|^.^......
.....|.........
....|^.^.^.....
....|..........
....^|^...^....
.....|.........
...^.^|..^.^...
......|........
..^..|^.....^..
.....|.........
.^.^.^|^.^...^.
......|........
In this example, in total, the particle ends up on 40 different timelines.

Apply the many-worlds interpretation of quantum tachyon splitting to your manifold diagram. In total, how many different timelines would a single tachyon particle end up on? 24743903847942
*/