package Day07;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.ListIterator;

public class Day07 {
    public static final char LASER_ORIGIN = 'S';
    public static final char LASER = '|';
    public static final char SPACE = '.';
    public static final char SPLITTER = '^';

    public static int getSolution() {
        int splitCount = 0;

        List<String> lines = loadLinesFromFile("src/Day07/input.txt");
        ListIterator<String> iterator = lines.listIterator();
        List<Integer> laserIndices = new ArrayList<>();
        while (iterator.hasNext()) {
            String line = iterator.next();
            if (laserIndices.isEmpty()) {
                laserIndices.add(line.indexOf(LASER_ORIGIN));
                continue;
            }
            List<Integer> nextLaserIndices = new ArrayList<>();
            String newLine = new String(line);
            for (Integer laserIndex : laserIndices) {                
                char currentChar = line.charAt(laserIndex);
                if (currentChar == SPACE) {
                    newLine = newLine.substring(0, laserIndex) + LASER + newLine.substring(laserIndex + 1, newLine.length());
                    if (!nextLaserIndices.contains(laserIndex)) {
                        nextLaserIndices.add(laserIndex);
                    }
                } else if (currentChar == SPLITTER) {
                    newLine = newLine.substring(0, laserIndex - 1) + LASER + SPLITTER + LASER + newLine.substring(laserIndex + 2, newLine.length());
                    if (!nextLaserIndices.contains(laserIndex - 1)) {
                        nextLaserIndices.add(laserIndex - 1);
                    }
                    if (!nextLaserIndices.contains(laserIndex + 1)) {
                        nextLaserIndices.add(laserIndex + 1);
                    }
                    splitCount++;
                }
            }
            iterator.set(newLine);
            laserIndices = nextLaserIndices;
        }

        return splitCount;
    }

    public static List<String> loadLinesFromFile(String filePath) {
        List<String> lines = new ArrayList<>();
        try (BufferedReader reader = new BufferedReader(new FileReader(filePath))) {
            String line;
            while ((line = reader.readLine()) != null) {
                lines.add(line);
            }
        } catch (IOException e) {
            System.err.println("Error reading file: " + e.getMessage());
        }
         return lines;
    }
}

/*
--- Day 7: Laboratories ---
You thank the cephalopods for the help and exit the trash compactor, finding yourself in the familiar halls of a North Pole research wing.

Based on the large sign that says "teleporter hub", they seem to be researching teleportation; you can't help but try it for yourself and step onto the large yellow teleporter pad.

Suddenly, you find yourself in an unfamiliar room! The room has no doors; the only way out is the teleporter. Unfortunately, the teleporter seems to be leaking magic smoke.

Since this is a teleporter lab, there are lots of spare parts, manuals, and diagnostic equipment lying around. After connecting one of the diagnostic tools, it helpfully displays 
error code 0H-N0, which apparently means that there's an issue with one of the tachyon manifolds.

You quickly locate a diagram of the tachyon manifold (your puzzle input). A tachyon beam enters the manifold at the location marked S; tachyon beams always move downward. Tachyon 
beams pass freely through empty space (.). However, if a tachyon beam encounters a splitter (^), the beam is stopped; instead, a new tachyon beam continues from the immediate left and from the immediate right of the splitter.

For example:

.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
In this example, the incoming tachyon beam (|) extends downward from S until it reaches the first splitter:

.......S.......
.......|.......
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
At that point, the original beam stops, and two new beams are emitted from the splitter:

.......S.......
.......|.......
......|^|......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
Those beams continue downward until they reach more splitters:

.......S.......
.......|.......
......|^|......
......|.|......
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
At this point, the two splitters create a total of only three tachyon beams, since they are both dumping tachyons into the same place between them:

.......S.......
.......|.......
......|^|......
......|.|......
.....|^|^|.....
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
This process continues until all of the tachyon beams reach a splitter or exit the manifold:

.......S.......
.......|.......
......|^|......
......|.|......
.....|^|^|.....
.....|.|.|.....
....|^|^|^|....
....|.|.|.|....
...|^|^|||^|...
...|.|.|||.|...
..|^|^|||^|^|..
..|.|.|||.|.|..
.|^|||^||.||^|.
.|.|||.||.||.|.
|^|^|^|^|^|||^|
|.|.|.|.|.|||.|
To repair the teleporter, you first need to understand the beam-splitting properties of the tachyon manifold. In this example, a tachyon beam is split a total of 21 times.

Analyze your manifold diagram. How many times will the beam be split? 1499
*/